<?php

namespace App\Modules\Notifications\Support;

final class NotificationTemplateCatalog
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function definitions(): array
    {
        $orderVars = ['user_name', 'order_id', 'order_reference', 'service_type', 'deep_link'];
        $paymentVars = ['user_name', 'order_id', 'order_reference', 'amount', 'currency', 'service_type', 'deep_link'];

        $existing = [
            self::entry(
                code: 'ORDER_CREATED',
                name: 'Order Created',
                category: NotificationTemplateCategories::ORDERS,
                description: 'Sent when a new booking is created and waiting for payment.',
                subject: 'Your booking {order_reference} was created — complete payment',
                body: 'Hello {user_name}, your booking #{order_reference} was created and is waiting for payment.',
                arSubject: 'تم إنشاء حجزك',
                arBody: 'مرحباً {user_name}، تم إنشاء حجزك #{order_reference} وهو بانتظار إتمام الدفع.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'order_status', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'ORDER_CONFIRMED',
                name: 'Order Confirmed',
                category: NotificationTemplateCategories::ORDERS,
                description: 'Generic order confirmation when no product-specific template applies.',
                subject: 'Order {order_reference} is confirmed',
                body: 'Hello {user_name}, your order #{order_reference} is now confirmed.',
                arSubject: 'تم تأكيد طلبك',
                arBody: 'مرحباً {user_name}، تم تأكيد طلبك #{order_reference}.',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'FLIGHT_TICKET_ISSUED',
                name: 'Flight Ticket Issued',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Sent when a flight order becomes ticketed.',
                subject: 'Your ticket for {order_reference} was issued',
                body: 'Hello {user_name}, your flight ticket #{order_reference} has been issued successfully.',
                arSubject: 'تم إصدار التذكرة',
                arBody: 'تذكرتك جاهزة — رقم الحجز: {order_reference}',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'HOTEL_BOOKING_CONFIRMED',
                name: 'Hotel Booking Confirmed',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Sent when a hotel booking is confirmed.',
                subject: 'Your hotel booking {order_reference} is confirmed',
                body: 'Hello {user_name}, your hotel booking #{order_reference} is confirmed.',
                arSubject: 'تم تأكيد حجز الفندق',
                arBody: 'حجزك #{order_reference} مؤكد.',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'INSURANCE_POLICY_ISSUED',
                name: 'Insurance Policy Issued',
                category: NotificationTemplateCategories::INSURANCE,
                description: 'Sent when an insurance policy document is ready.',
                subject: 'Your insurance policy {order_reference} was issued',
                body: 'Hello {user_name}, your insurance policy #{order_reference} has been issued successfully.',
                arSubject: 'تم إصدار وثيقة التأمين',
                arBody: 'وثيقة التأمين الخاصة بك جاهزة — رقم المرجع {order_reference}.',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'ESIM_ORDER_CONFIRMED',
                name: 'eSIM Order Confirmed',
                category: NotificationTemplateCategories::ORDERS,
                description: 'Sent when an eSIM order is confirmed.',
                subject: 'Your eSIM order {order_reference} is ready',
                body: 'Hello {user_name}, your eSIM order #{order_reference} is confirmed.',
                arSubject: 'تم تأكيد طلب eSIM',
                arBody: 'مرحباً {user_name}، طلب eSIM #{order_reference} جاهز.',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'PAYMENT_SUCCEEDED',
                name: 'Payment Succeeded',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Sent after a successful payment for an order.',
                subject: 'Payment received for order {order_reference}',
                body: 'Hello {user_name}, we received {amount} {currency} for order #{order_reference}.',
                arSubject: 'تم الدفع بنجاح',
                arBody: 'تم تأكيد دفع طلبك بمبلغ {amount} {currency} — مرجع {order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::EMAIL, NotificationChannels::IN_APP],
                variables: $paymentVars,
            ),
            self::entry(
                code: 'PAYMENT_FAILED',
                name: 'Payment Failed',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Sent when payment fails or the order moves to failed status.',
                subject: 'Payment failed for order {order_reference}',
                body: 'Hello {user_name}, payment for order #{order_reference} failed. Please try again. {reason}',
                arSubject: 'فشل الدفع',
                arBody: 'تعذّر إتمام الدفع للطلب #{order_reference}. يرجى المحاولة مرة أخرى. {reason}',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_id', 'order_reference', 'reason', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'REFUND_ISSUED',
                name: 'Refund Issued',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Sent when a refund is processed for an order.',
                subject: 'Refund issued for order {order_reference}',
                body: 'Hello {user_name}, we issued a refund of {amount} {currency} for order #{order_reference}. Reason: {reason}',
                arSubject: 'تم إرجاع المبلغ',
                arBody: 'تم إرجاع {amount} {currency} إلى حسابك — مرجع {order_reference}. السبب: {reason}',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'amount', 'currency', 'reason', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_STATUS_UPDATED',
                name: 'Flight Status Updated',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Sent when flight details change during provider sync.',
                subject: 'Update on your flight {order_reference}',
                body: 'Hello {user_name}, {summary} Booking #{order_reference}.',
                arSubject: 'تحديث حالة الرحلة',
                arBody: 'تغيّرت حالة رحلتك — {summary} — مرجع {order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_id', 'order_reference', 'summary', 'from_value', 'to_value', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_TIME_CHANGED',
                name: 'Flight departure time changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Sent when the airline updates departure time. Not gated by promotional preferences.',
                subject: 'Your departure time was updated',
                body: 'Departure for {route} changed from {from_value} to {to_value}.',
                arSubject: 'تم تغيير موعد رحلتك',
                arBody: 'تغيّر إقلاع {route} من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_ARRIVAL_CHANGED',
                name: 'Flight arrival time changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Sent when arrival time changes.',
                subject: 'Your arrival time was updated',
                body: 'Arrival for {route} changed from {from_value} to {to_value}.',
                arSubject: 'تم تغيير موعد الوصول',
                arBody: 'تغيّر وصول {route} من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_CHANGED',
                name: 'Flight details changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Route or flight number changed.',
                subject: 'Your flight details were updated',
                body: 'Your flight {route} was updated: {from_value} → {to_value}.',
                arSubject: 'تم تحديث تفاصيل رحلتك',
                arBody: 'تم تحديث رحلتك {route}: {from_value} → {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_GATE_CHANGED',
                name: 'Flight gate changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Departure gate changed.',
                subject: 'Your departure gate was updated',
                body: 'Gate changed from {from_value} to {to_value} for {route}.',
                arSubject: 'تم تغيير بوابة الرحلة',
                arBody: 'تغيّرت البوابة من {from_value} إلى {to_value} لرحلة {route}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_TERMINAL_CHANGED',
                name: 'Flight terminal changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Departure terminal changed.',
                subject: 'Your departure terminal was updated',
                body: 'Terminal changed from {from_value} to {to_value} for {route}.',
                arSubject: 'تم تغيير مبنى المغادرة',
                arBody: 'تغيّر المبنى/الصالة من {from_value} إلى {to_value} لرحلة {route}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_SEAT_CHANGED',
                name: 'Flight seat changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Assigned seat changed by the airline.',
                subject: 'Your seat was updated',
                body: 'Your seat changed from {from_value} to {to_value}.',
                arSubject: 'تم تغيير مقعدك',
                arBody: 'تغيّر مقعدك من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_CLASS_CHANGED',
                name: 'Flight class changed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Cabin/class changed.',
                subject: 'Your travel class was updated',
                body: 'Your class changed from {from_value} to {to_value}.',
                arSubject: 'تم تحديث درجة سفرك',
                arBody: 'تغيّرت درجة السفر من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_DELAYED',
                name: 'Flight delayed',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Operational. Flight delayed.',
                subject: 'Your flight {order_reference} is delayed',
                body: 'Your flight {route} is delayed. New time: {to_value}.',
                arSubject: 'رحلتك متأخرة',
                arBody: 'رحلتك {route} متأخرة. الوقت الجديد: {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_CANCELLED',
                name: 'Flight cancelled by airline',
                category: NotificationTemplateCategories::FLIGHTS,
                description: 'Critical operational. Airline cancelled the flight. Always delivered.',
                subject: 'Your flight {order_reference} was cancelled',
                body: '{route} was cancelled by the airline. Open the app to view alternatives or request a refund.',
                arSubject: 'تم إلغاء رحلتك',
                arBody: 'أُلغيت رحلتك {route} من شركة الطيران. يمكنك عرض البدائل أو طلب الاسترداد.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'route', 'origin', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'BOOKING_CANCELLED',
                name: 'Booking cancelled',
                category: NotificationTemplateCategories::ORDERS,
                description: 'Transactional. Customer or admin cancelled the booking.',
                subject: 'Your booking {order_reference} was cancelled',
                body: 'Hello {user_name}, booking #{order_reference} was cancelled successfully.',
                arSubject: 'تم إلغاء حجزك',
                arBody: 'مرحباً {user_name}، تم إلغاء حجزك #{order_reference} بنجاح.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: $orderVars,
            ),
            self::entry(
                code: 'BOOKING_FAILED',
                name: 'Booking failed',
                category: NotificationTemplateCategories::ORDERS,
                description: 'Transactional. Paid booking could not be confirmed.',
                subject: 'We could not confirm booking {order_reference}',
                body: 'Hello {user_name}, we could not confirm booking #{order_reference}. {reason}',
                arSubject: 'تعذر تأكيد حجزك',
                arBody: 'مرحباً {user_name}، تعذر تأكيد حجزك #{order_reference}. {reason}',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_id', 'order_reference', 'reason', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'HOTEL_BOOKING_CANCELLED',
                name: 'Hotel booking cancelled',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Transactional/operational hotel cancellation.',
                subject: 'Your hotel booking {order_reference} was cancelled',
                body: 'Hello {user_name}, hotel booking #{order_reference} was cancelled.',
                arSubject: 'تم إلغاء حجز الفندق',
                arBody: 'مرحباً {user_name}، تم إلغاء حجز الفندق #{order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: $orderVars,
            ),
            self::entry(
                code: 'HOTEL_BOOKING_MODIFIED',
                name: 'Hotel booking modified',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Operational. Hotel booking details changed.',
                subject: 'Your hotel booking was updated',
                body: 'Hello {user_name}, hotel booking #{order_reference} was updated. {summary}',
                arSubject: 'تم تعديل حجز الفندق',
                arBody: 'مرحباً {user_name}، تم تحديث حجز الفندق #{order_reference}. {summary}',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_reference', 'summary', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'HOTEL_CHECKIN_CHANGED',
                name: 'Hotel check-in changed',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Operational. Check-in date changed.',
                subject: 'Your hotel check-in date was updated',
                body: 'Check-in for #{order_reference} changed from {from_value} to {to_value}.',
                arSubject: 'تم تغيير تاريخ تسجيل الوصول',
                arBody: 'تغيّر check-in لحجز #{order_reference} من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_reference', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'HOTEL_CHECKOUT_CHANGED',
                name: 'Hotel check-out changed',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Operational. Check-out date changed.',
                subject: 'Your hotel check-out date was updated',
                body: 'Check-out for #{order_reference} changed from {from_value} to {to_value}.',
                arSubject: 'تم تغيير تاريخ المغادرة',
                arBody: 'تغيّر check-out لحجز #{order_reference} من {from_value} إلى {to_value}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_reference', 'from_value', 'to_value', 'deep_link'],
            ),
            self::entry(
                code: 'HOTEL_CANCELLATION_DEADLINE_REMINDER',
                name: 'Hotel free-cancellation deadline',
                category: NotificationTemplateCategories::HOTELS,
                description: 'Journey reminder before free cancellation expires.',
                subject: 'Last chance to cancel {order_reference} for free',
                body: 'You can still cancel hotel booking #{order_reference} until {deadline} without fees.',
                arSubject: 'آخر فرصة للإلغاء المجاني',
                arBody: 'يمكنك إلغاء حجز الفندق #{order_reference} حتى {deadline} دون رسوم.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_reference', 'deadline', 'deep_link'],
            ),
            self::entry(
                code: 'PAYMENT_EXPIRED',
                name: 'Payment window expired',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Transactional. Unpaid booking payment window expired.',
                subject: 'Payment window expired for {order_reference}',
                body: 'Hello {user_name}, the payment window for booking #{order_reference} has expired.',
                arSubject: 'انتهت مهلة الدفع',
                arBody: 'مرحباً {user_name}، انتهت مهلة الدفع لحجز #{order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: $orderVars,
            ),
            self::entry(
                code: 'REFUND_INITIATED',
                name: 'Refund initiated',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Transactional. Refund processing started.',
                subject: 'We started refunding {amount} {currency}',
                body: 'Hello {user_name}, we started processing a refund of {amount} {currency} for order #{order_reference}.',
                arSubject: 'بدأنا معالجة الاسترداد',
                arBody: 'مرحباً {user_name}، بدأنا معالجة استرداد {amount} {currency} لحجز #{order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'amount', 'currency', 'deep_link'],
            ),
            self::entry(
                code: 'REFUND_COMPLETED',
                name: 'Refund completed',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Alias-quality copy for a completed refund. Executed refunds currently send REFUND_ISSUED.',
                subject: 'Refund completed for {order_reference}',
                body: 'We refunded {amount} {currency} for order #{order_reference}.',
                arSubject: 'تم استرداد المبلغ',
                arBody: 'تم استرداد {amount} {currency} لحجز #{order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'amount', 'currency', 'deep_link'],
            ),
            self::entry(
                code: 'REFUND_FAILED',
                name: 'Refund failed',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Transactional. Refund could not be completed.',
                subject: 'We could not complete your refund',
                body: 'Hello {user_name}, we could not complete the refund of {amount} {currency} for order #{order_reference}. {reason}',
                arSubject: 'تعذر إكمال الاسترداد',
                arBody: 'مرحباً {user_name}، تعذر استرداد {amount} {currency} لحجز #{order_reference}. سنتواصل معك للمساعدة.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_reference', 'amount', 'currency', 'reason', 'deep_link'],
            ),
            self::entry(
                code: 'FLIGHT_REMINDER_24H',
                name: 'Flight Reminder 24h',
                category: NotificationTemplateCategories::REMINDERS,
                description: 'Scheduled reminder 24 hours before departure. Embeds a trip checklist / next-best-offer on the same card.',
                subject: 'Your flight to {destination} is tomorrow',
                body: 'Hello {user_name}, {route} departs tomorrow at {departure_clock}. {checklist_hint}',
                arSubject: 'رحلتك إلى {destination} غداً',
                arBody: 'مرحباً {user_name}، رحلتك {route} غداً الساعة {departure_clock}. {checklist_hint_ar}',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_id', 'order_reference', 'origin', 'destination', 'route', 'departure_clock', 'deep_link', 'reminder_window', 'checklist_hint', 'checklist_hint_ar', 'missing_labels'],
            ),
            self::entry(
                code: 'FLIGHT_REMINDER_3H',
                name: 'Flight Reminder 3h',
                category: NotificationTemplateCategories::REMINDERS,
                description: 'Smart 3-hour reminder with optional eSIM/insurance CTAs on the same journey card — not separate pushes.',
                subject: 'Your flight to {destination} is in 3 hours',
                body: '{route} departs at {departure_clock}. Head to the airport now. Booking {order_reference}.',
                arSubject: 'رحلتك إلى {destination} بعد 3 ساعات',
                arBody: '{route} الإقلاع الساعة {departure_clock}. ننصحك بالتوجه إلى المطار الآن. مرجع {order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'origin', 'destination', 'route', 'departure_clock', 'deep_link', 'reminder_window'],
            ),
            self::entry(
                code: 'FLIGHT_REMINDER_1H',
                name: 'Flight Reminder 1h',
                category: NotificationTemplateCategories::REMINDERS,
                description: 'Reminder only — time to go to the airport. Deep link /my-orders/{order_id}.',
                subject: 'Your flight is in 1 hour',
                body: 'Time to head to the airport. {route} departs at {departure_clock}.',
                arSubject: 'رحلتك بعد ساعة',
                arBody: 'حان وقت التوجه إلى المطار. {route} الإقلاع الساعة {departure_clock}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'origin', 'destination', 'route', 'departure_clock', 'deep_link', 'reminder_window'],
            ),
            self::entry(
                code: 'HOTEL_CHECKIN_REMINDER_24H',
                name: 'Hotel Check-in Reminder 24h',
                category: NotificationTemplateCategories::REMINDERS,
                description: 'Reminder 24 hours before hotel check-in. Requires hotel + booking_reminders topics.',
                subject: 'Your stay is tomorrow — {order_reference}',
                body: 'Hello {user_name}, check-in for hotel booking #{order_reference} is tomorrow.',
                arSubject: 'تذكير تسجيل الوصول',
                arBody: 'غداً موعد check-in لحجزك #{order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'order_id', 'order_reference', 'service_type', 'deep_link', 'reminder_window'],
            ),
            self::entry(
                code: 'PAYMENT_REMINDER',
                name: 'Complete Payment Reminder',
                category: NotificationTemplateCategories::PAYMENTS,
                description: 'Nudges the customer to finish payment if the booking is still unpaid.',
                subject: 'Complete payment for {order_reference}',
                body: 'Hello {user_name}, your booking #{order_reference} is still waiting for payment. Complete it to confirm your trip.',
                arSubject: 'أكمل الدفع لحجزك',
                arBody: 'مرحباً {user_name}، حجزك #{order_reference} ما زال بانتظار الدفع. أكمل الدفع لتأكيد الرحلة.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'service_type', 'deep_link'],
            ),
            self::entry(
                code: 'DESTINATION_ARRIVAL',
                name: 'Destination arrival',
                category: NotificationTemplateCategories::REMINDERS,
                description: 'Triggered from flight.arrival_datetime (no GPS). May include a hotel CTA on the same card.',
                subject: 'Welcome to {destination}',
                body: 'You have arrived in {destination}. Open the app if you need a hotel nearby.',
                arSubject: 'أهلاً بك في {destination}',
                arBody: 'وصلت إلى {destination}. إذا احتجت فندقاً قريباً، اكتشفه من التطبيق واحجز مباشرة.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'origin', 'destination', 'arrival_clock', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_ESIM',
                name: 'Offer eSIM',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Embedded on the 3h journey card when destination country is known and the user has no eSIM for that country.',
                subject: 'Need internet in {destination}?',
                body: 'Activate an eSIM before you fly and stay connected from the moment you land.',
                arSubject: 'تحتاج إنترنت في {destination}؟',
                arBody: 'فعّل eSIM قبل السفر وخليك متصل من أول ما توصل.',
                channels: [NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'destination', 'destination_country', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_INSURANCE',
                name: 'Offer insurance',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Embedded on the 3h journey card when the flight has no insurance linked to this trip.',
                subject: 'Protect your trip to {destination}',
                body: 'Add travel insurance before your departure.',
                arSubject: 'أمّن رحلتك إلى {destination}',
                arBody: 'احصل على تغطية تأمينية قبل موعد سفرك.',
                channels: [NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_ESIM_FOR_TRIP',
                name: 'Offer eSIM for trip',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Suggests buying an eSIM before departure. Skipped if the customer already has an eSIM order.',
                subject: 'Stay connected in {destination}',
                body: 'Hello {user_name}, get an eSIM for {destination} before you fly ({order_reference}) and stay online on arrival.',
                arSubject: 'إنترنت جاهز في وجهتك',
                arBody: 'مرحباً {user_name}، اشترِ شريحة eSIM لـ {destination} قبل رحلتك ({order_reference}) وابقَ متصلاً فور الوصول.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_INSURANCE_FOR_TRIP',
                name: 'Offer travel insurance',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Suggests travel insurance before departure. Skipped if the customer already has insurance.',
                subject: 'Protect your trip to {destination}',
                body: 'Hello {user_name}, add travel insurance for {destination} (booking {order_reference}) before you fly.',
                arSubject: 'أمّن رحلتك',
                arBody: 'مرحباً {user_name}، أضف تأميناً لرحلتك إلى {destination} (حجز {order_reference}) قبل الإقلاع.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_HOTELS_AT_DESTINATION',
                name: 'Offer hotels at destination',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Sent around landing time to suggest hotels in the destination city/zone.',
                subject: 'Hotels waiting in {destination}',
                body: 'Welcome to {destination}. Find a hotel near you for tonight — from booking {order_reference}.',
                arSubject: 'فنادق في وجهتك',
                arBody: 'أهلاً بك في {destination}. احجز فندقاً قريباً منك لهذه الليلة — حجز {order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_CARS_AT_DESTINATION',
                name: 'Offer car rental at destination',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Suggests a car rental after landing. Respects car_rental preference.',
                subject: 'Need a car in {destination}?',
                body: 'You have landed in {destination}. Rent a car for your stay — booking {order_reference}.',
                arSubject: 'سيارة في وجهتك؟',
                arBody: 'وصلت إلى {destination}. استأجر سيارة لإقامتك — حجز {order_reference}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'POST_TRIP_THANKS',
                name: 'Post-trip thanks',
                category: NotificationTemplateCategories::LOYALTY,
                description: 'Sent about 3 days after arrival. Next-best-offer (next trip / loyalty) is on the same card.',
                subject: 'How was {destination}?',
                body: 'Hello {user_name}, welcome back from {destination}. Open the app to collect points or book your next trip.',
                arSubject: 'كيف كانت رحلتك؟',
                arBody: 'مرحباً {user_name}، أهلاً بعودتك من {destination}. افتح التطبيق لجمع نقاطك أو حجز رحلتك القادمة.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'order_id', 'order_reference', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'OFFER_RETURN_FLIGHT',
                name: 'Offer return flight',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Next-best-offer after a one-way ticket: suggest booking the return.',
                subject: 'You __BookNowD__ the outbound. What about the return?',
                body: 'Find a return from {destination} before fares go up.',
                arSubject: 'حجزت الذهاب، ماذا عن العودة؟',
                arBody: 'ابحث عن رحلة العودة من {destination} قبل ارتفاع الأسعار.',
                channels: [NotificationChannels::IN_APP],
                variables: ['user_name', 'origin', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'POST_TRIP_NEXT',
                name: 'Post-trip next booking',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Embedded after the trip to start the next search from the destination.',
                subject: 'Ready for your next trip from {destination}?',
                body: 'Discover BookNow deals departing from {destination}.',
                arSubject: 'جاهز لرحلتك القادمة؟',
                arBody: 'اكتشف عروض BookNow من {destination}.',
                channels: [NotificationChannels::IN_APP],
                variables: ['user_name', 'destination', 'deep_link'],
            ),
            self::entry(
                code: 'LOYALTY_NEAR_REWARD',
                name: 'Loyalty near reward',
                category: NotificationTemplateCategories::LOYALTY,
                description: 'Embedded when loyalty progress is at least 80% toward the next tier.',
                subject: 'You are close to your next reward',
                body: 'Keep going — your next BookNow reward is almost unlocked.',
                arSubject: 'باقي قليل وتفتح مكافأتك',
                arBody: 'استمر — مكافأتك التالية في BookNow اقتربت.',
                channels: [NotificationChannels::IN_APP],
                variables: ['user_name', 'deep_link'],
            ),
            self::entry(
                code: 'ABANDONED_FLIGHT_SEARCH',
                name: 'Abandoned flight search',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Follow-up when the traveler searched a route and left without booking. Requires mobile to POST the search intent.',
                subject: 'Your trip to {destination} is still available',
                body: 'Fares to {destination} start from {price} {currency}.',
                arSubject: 'ما زالت رحلتك إلى {destination} متاحة',
                arBody: 'تبدأ الأسعار إلى {destination} من {price} {currency}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'origin', 'destination', 'route', 'departure_date', 'price', 'currency', 'deep_link'],
            ),
            self::entry(
                code: 'PRICE_ALERT_HIT',
                name: 'Price alert hit',
                category: NotificationTemplateCategories::OFFERS,
                description: 'Sent when a watched route drops to or below the traveler\'s target price.',
                subject: 'Your watched fare to {destination} is now {price} {currency}',
                body: 'The trip you are watching is now within your budget of {target_price} {currency}.',
                arSubject: 'السعر إلى {destination} وصل إلى {price} {currency}',
                arBody: 'رحلتك التي تراقبها أصبحت ضمن ميزانيتك {target_price} {currency}.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'origin', 'destination', 'route', 'departure_date', 'price', 'target_price', 'currency', 'deep_link'],
            ),
            self::entry(
                code: 'LOGIN_ALERT',
                name: 'Login Alert',
                category: NotificationTemplateCategories::SECURITY,
                description: 'Security alert when a new sign-in is detected. Respects login_alerts preference.',
                subject: 'New login to your account',
                body: 'A new sign-in was detected on {device_name}{ip}. If this was not you, change your password immediately.',
                arSubject: 'تسجيل دخول جديد',
                arBody: 'تم تسجيل الدخول إلى حسابك من {device_name}{ip}. إذا لم تكن أنت، غيّر كلمة المرور فوراً.',
                channels: [NotificationChannels::PUSH, NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'device_name', 'ip', 'deep_link'],
            ),
            self::entry(
                code: 'SUPPORT_TICKET_CREATED_CUSTOMER',
                name: 'Support Ticket Created',
                category: NotificationTemplateCategories::SUPPORT,
                description: 'Confirms a new support ticket for the customer.',
                subject: 'Support ticket {ticket_number} was created',
                body: 'Hello {user_name}, your support ticket {ticket_number} was opened successfully. Our team will update you shortly.',
                arSubject: 'تم فتح تذكرة دعم',
                arBody: 'مرحباً {user_name}، تم فتح تذكرة الدعم {ticket_number} بنجاح. سنتابع معك قريباً.',
                channels: [NotificationChannels::IN_APP, NotificationChannels::EMAIL],
                variables: ['user_name', 'ticket_number', 'ticket_subject', 'deep_link'],
            ),
            self::entry(
                code: 'SUPPORT_TICKET_REPLIED_CUSTOMER',
                name: 'Support Ticket Reply',
                category: NotificationTemplateCategories::SUPPORT,
                description: 'Notifies the customer when support replies to their ticket.',
                subject: 'New update on ticket {ticket_number}',
                body: 'Hello {user_name}, support replied to ticket {ticket_number}.',
                arSubject: 'رد جديد على تذكرتك',
                arBody: 'مرحباً {user_name}، رد فريق الدعم على تذكرتك {ticket_number}. اضغط للتفاصيل.',
                channels: [NotificationChannels::IN_APP, NotificationChannels::PUSH],
                variables: ['user_name', 'ticket_number', 'deep_link'],
            ),
            self::entry(
                code: 'LOYALTY_TIER_CHANGED',
                name: 'Loyalty Tier Changed',
                category: NotificationTemplateCategories::LOYALTY,
                description: 'Sent when the customer loyalty tier changes.',
                subject: 'Your loyalty tier is now {tier_name}',
                body: 'Hello {user_name}, your loyalty tier changed from {from_tier} to {tier_name}.',
                arSubject: 'تغيّر مستوى الولاء',
                arBody: 'مرحباً {user_name}، تغيّر مستوى الولاء من {from_tier} إلى {tier_name}.',
                channels: [NotificationChannels::EMAIL, NotificationChannels::PUSH, NotificationChannels::IN_APP],
                variables: ['user_name', 'from_tier', 'tier_name', 'deep_link'],
            ),
        ];

        return array_merge($existing, array_map(
            static fn (array $item): array => self::entry(
                code: $item['code'],
                name: $item['name'],
                category: $item['category'],
                description: $item['description'],
                subject: $item['subject'],
                body: $item['body'],
                arSubject: $item['ar_subject'],
                arBody: $item['ar_body'],
                channels: $item['channels'],
                variables: $item['variables'],
            ),
            NotificationActionCatalog::templates(),
        ));
    }

    /**
     * @param  list<string>  $channels
     * @param  list<string>  $variables
     * @return array<string, mixed>
     */
    private static function entry(
        string $code,
        string $name,
        string $category,
        string $description,
        string $subject,
        string $body,
        string $arSubject,
        string $arBody,
        array $channels,
        array $variables,
    ): array {
        return [
            'code' => $code,
            'name' => $name,
            'category' => $category,
            'description' => $description,
            'subject' => $subject,
            'body' => $body,
            'translations' => [
                NotificationLocales::AR => [
                    'subject' => $arSubject,
                    'body' => $arBody,
                ],
            ],
            'channels' => $channels,
            'variables' => $variables,
        ];
    }
}
