export const emptyAirportForm = () => ({
    iata_code: '',
    icao_code: '',
    name_en: '',
    name_ar: '',
    name_fr: '',
    city_en: '',
    city_ar: '',
    city_fr: '',
    country_iso2: '',
    country_name_en: '',
    country_name_ar: '',
    country_name_fr: '',
    type: '',
    scheduled_service: '',
    latitude_deg: '',
    longitude_deg: '',
    translation_status: '',
});

export const airportFormFromRecord = (airport = {}) => ({
    iata_code: airport.iata_code ?? '',
    icao_code: airport.icao_code ?? '',
    name_en: airport.name_en ?? '',
    name_ar: airport.name_ar ?? '',
    name_fr: airport.name_fr ?? '',
    city_en: airport.city_en ?? '',
    city_ar: airport.city_ar ?? '',
    city_fr: airport.city_fr ?? '',
    country_iso2: airport.country_iso2 ?? '',
    country_name_en: airport.country_name_en ?? '',
    country_name_ar: airport.country_name_ar ?? '',
    country_name_fr: airport.country_name_fr ?? '',
    type: airport.type ?? '',
    scheduled_service: airport.scheduled_service ?? '',
    latitude_deg: airport.latitude_deg ?? '',
    longitude_deg: airport.longitude_deg ?? '',
    translation_status: airport.translation_status ?? '',
});
